hmcts/ccd-case-migration-starter

.travis.yml, build.gradle
None
Add automatic uploads to Bintray to CI pipeline
```
[ ] Yes
[x] No
```
=> Add uploads to Bintray to CI pipeline

modules/processor/build.gradle
Bump ccd to be aligned with latest requirement.
=> chore: bump the ccd version of the client

build.gradle, charts/ccd-migration/Chart.yaml, charts/ccd-migration/values.yaml, config/owasp/suppressions.xml, modules/domain/build.gradle, modules/processor/build.gradle, modules/processor/src/main/java/uk/gov/hmcts/reform/migration/ccd/CoreCaseDataService.java, modules/processor/src/main/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImpl.java, modules/processor/src/main/resources/application.properties, modules/processor/src/test/java/uk/gov/hmcts/reform/migration/service/DataMigrationServiceImplTest.java
=> Fixed issue with image loading

build.gradle, config/owasp/suppressions.xml
=> Ccd 3667: CVE Issues

src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessor.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/migration/CaseMigrationProcessorTest.java
=> Ccd 3665: Ensure that the code has a limit to the number of cases that can be processed per invocation

README.md
https://tools.hmcts.net/jira/browse/CCD-3741
Update migration starter README file.
See also https://tools.hmcts.net/confluence/display/RCCD/CCD+Data+Migration+Process
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-3741: Update migration starter README file

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4043
Replace fasterxml.jackson release candidate with prod-ready version
```
[ ] Yes
[ x] No
```
=> CCD-4043 Fasterxml Jackson Upgrade

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4485
Suppression for CVE-2023-20861
```
[ ] Yes
[X] No
```
=> CCD-4485 : Update suppressions.xml

config/owasp/suppressions.xml
NA - To fix master build
CVE-2023-20860- Update suppressions.xml
```
[ ] Yes
[X] No
```
=> CVE-2023-20860- Update suppressions.xml

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4584
CCD-4584 : suppress CVE-2023-20863
```
[ ] Yes
[X] No
```
=> CCD-4584 : suppress CVE-2023-20863

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4607
Suppress CVE-2023-20873, CVE-2023-20862
```
[ ] Yes
[X] No
```
=> CCD-4607 : Update suppressions.xml

.github/renovate.json, Dockerfile
=> CCD-4598 Update renovate

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4607
bumped spring-security to 5.7.8
```
[ ] Yes
[X] No
```
=> CCD-4607 : Fix for CVE-2023-20862

src/main/java/uk/gov/hmcts/reform/migration/CaseMigrationRunner.java
=> Add feign client info

.github/renovate.json, lib/applicationinsights.json
=> CCD-3710 AppInsights Health Sampling

build.gradle
https://tools.hmcts.net/jira/browse/CCD-4454
Bumped snakeyaml to 2.0
```
[ ] Yes
[X] No
```
=> CCD-4454-Fix-CVE-2022-1471

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4771
bumped jackson.version, removed suppression
```
[ ] Yes
[X] No
```
=> CCD-4771 : Fix CVE-2023-35116 

build.gradle, config/owasp/suppressions.xml
[CCD-5208](https://tools.hmcts.net/jira/browse/CCD-5208)
Upped the version of Spring Security to resolve CVE
```
[ ] Yes
[X] No
```
=> CVE fixes 280224

config/owasp/suppressions.xml
=> CCD-5312 Tidy up

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5201
Removed suppression as library version had already been updated to resolve CVE
```
[ ] Yes
[X] No
```
=> CCD-5201 Spring Security already updated so removed CVE suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5953
bumped spring security
```
[ ] Yes
[X] No
```
=> CCD-5953 : Fix CVE-2023-52428

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5923
Bumped jackson
```
[ ] Yes
[X] No
```
=> CCD 5923 : Fix CVE 2023-351161

charts/ccd-migration/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```
=> CCD-6193 update base chart version

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6285
https://tools.hmcts.net/jira/browse/CCD-6278
```
[ ] Yes
[X] No
```
=> CCD-6285 Suppress CVE
